### ISSUE TITLE
Update to pull Jenkins:latest

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/adb-openshift-runtime#16]
https://github.com/redhat-kontinuity/adb-openshift-runtime/blob/master/Vagrantfile#L116

Needs to be:

openshift/jenkins-1-centos7:latest

**Comment by ALRubinger** [comment]
Also we need to update the template file here in @tnozicka namespace:

https://github.com/redhat-kontinuity/adb-openshift-runtime/blob/master/Vagrantfile#L79

...to reference :latest and not :dev 

https://github.com/tnozicka/adb-utils/blob/update-jenkins-next-templates/services/openshift/templates/adb/jenkins-ephemeral-next-template.json#L67

**Comment by xcoulon** [comment]
I just submitted https://github.com/redhat-kontinuity/adb-openshift-runtime/pull/17 for the first part

**Comment by xcoulon** [comment]
@tnozicka https://github.com/tnozicka/adb-utils/pull/1 covers the 2 part of this issue.

**Comment by tnozicka** [comment]
fixed by https://github.com/redhat-kontinuity/adb-openshift-runtime/commit/d4d25977708afe3b2e4b4493cbf40d779d260868

**Comment by tnozicka** [comment]
@ALRubinger  [close]
