### ISSUE TITLE
Pre-pull Docker images

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/adb-openshift-runtime#8]
The first build takes longer than we want as it involves pulling Docker images not yet in the registry; additionally the user doesn't have great indication that this is happening or how long it'll take.

We can invoke a pre-load by having Vagrant pull the docker images during startup so that the runtime is more efficient.

Images to pull:

registry.access.redhat.com/jboss-eap-7/eap70-openshift:latest
maven-jenkins-slave
...others?

**Comment by tnozicka** [comment]
- docker.io/redhatdevelopers/catapult
 - docker.io/openshift/jenkins-1-centos7:dev
 - docker.io/redhatdistortion/maven-jenkins-slave
 - registry.access.redhat.com/jboss-eap-7/eap70-openshift
